title: Application Security Blog
tagline: >-
  A blog about application security fundamentals.
description: >-
  Posts and notes about security best practices.
lang: en
timezone: Asia/Ho_Chi_Minh

url: "https://haidang17-ia.github.io"
baseurl: ""  

remote_theme: cotes2020/jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/

# Enable post list rendering
collections:
  posts:
    output: true

# Author info (tùy chỉnh)
author:
  name: Dang
  bio: >-
    A learner in application security.
    # force rebuild

